### PR TITLE
gave Cong. Staffers ability to skip AOC_FLOWN status

### PR DESCRIPTION
**Pull request by mertbagt**
image

done

Also:

Previously if the Order Status was complete, the UI buttons would not be rendered.

Now if the Order is manually advanced to complete by a user, the buttons are rendered so that the user can revert their change if needed.  If the Order was already at complete before a user takes any action, the buttons are not rendered as before.

### CODE REVIEW

**Comment by Tmstone** [comment]
Requirements were incorrect and security rules were changed on Feb. 23. We are closing this request without merging. This decision was made in the meeting on March 2, 2022.

**Comment by mertbagt** [comment]
looking for clarification on requirements

**Comment by thadk** [comment]
image

**Comment by thadk** [comment]
- Bold "skip", 
- bigger test on the update message that we want them to do
- bold on the update button (we want them to press it)
- rename functions
- remove "next #4"

**Review by thadk — APPROVED** [review]

**Pull request merged**
