### PR TITLE
basic layout for Scan page

### PR DESCRIPTION
**Pull request by mertbagt**
laid out a page to simulate where user will land after scanning a QR code

next step: when status is sent from backend as part of response.data, use that to calculate next status in preparation for updating the backend if user wants to increment status after scanning.

### CODE REVIEW

**Comment by mertbagt** [comment]
receiving status on frontend; will make a sub-branch to start integrating the ability to increment status there.

**Comment by ethanstrominger** [comment]
Looks good.  Before merging, please resolve the merge conflict.  There is a merge conflict in OrderForm.js.  Depending on the amount of changes you did you should either apply the changes you did on top of OrderForm.js (get it from main branch) or look at the last few changes in OrderForm.js and apply it on top of yours.

**Comment by ethanstrominger** [comment]
When you resolve the conflicts, please push to the same branch and let me know so I can merge right away.

**Comment by ethanstrominger** [comment]
Other changes:
- I could not see OrderNumber or other info about the Order - maybe that is intentional and you plan to do it later.
- You only need the SetOrder function.  Better would be a SetStatus function.  
- I recommend creating a new screen rather than reuse the OrderForm since there is a lot of code on the OrderForm that is not relevant to a mostly read only view.

**Review by ethanstrominger — CHANGES_REQUESTED** [review]
See comments above.

**Pull request closed without merging**
