### PR TITLE
Status Drop Downs

### PR DESCRIPTION
**Pull request by mertbagt**
I split my work into 2 parts to make it easier to merge: this is part 1 primarily focused on the Status drop-down with my other work to come later.

I had previously written some logic to filter drop-down options per 'pseudo user login info' but now that we have a real user info db coming online, a lot of that will get rewritten.

### CODE REVIEW

**Comment by mertbagt** [comment]
Part of the reason why the Status dropdown looks different is that there are some subtle mismatches that sometimes happen with the old drop downs.

select Add (navbar), pick a unused order number, select CT, select CT-02, select FL

image

*looks valid*, hit Submit

image

go to Orders

image

Realize that using the <select> / top of the drop down to display the current component state to the user isn't reliable.

**Comment by mertbagt** [comment]
image

-----

image

-----

image

By displaying the info independently of the drop-down, my goal is to force the display to show what is currently in state.

Using a more accurate display to note and handle misaligned USState/Cong Office edge cases and some message handling will be part of my follow on Pull Request, if this PR passes.

Definitely wanted the team to see my alternate display in case there are drawbacks to this approach I missed.

**Comment by thadk** [comment]
I really like the affirmative feel of the way you did it! The one thing I guess would be nice is some visual cue that you've changed the record locally and it is now "dirty" and your changes will be lost unless you press update.

> Part of the reason why the Status dropdown looks different... 
Was this modified in the PR, think maybe not—if not, could you help to make an issue out of it, please?

**Review by thadk — APPROVED** [review]
Thanks for thinking ahead to the DB!

**Pull request merged**
